module.exports = {
	"html": "gulp html",
	"sass": "gulp sass",
	"temp": "gulp temp",
	"js": "gulp js",
	"html-w": "gulp html-w",
	"sass-w": "gulp sass-w",
	"temp-w": "gulp temp-w",
	"js-w": "gulp js-w",
	"compile-all": "gulp all",
	"livereload": "gulp livereload",
	"env-debug-hard": "node build/setenv debug-hard",
	"env-debug-normal": "node build/setenv debug-normal",
	"env-debug-light": "node build/setenv debug-light",
	"env-release": "node build/setenv release-light",
	"showenv": "node build/showenv",
	"libcss": "node build/libs css",
	"libjs": "node build/libs js",
	"build-libs": "npm run libcss && npm run libjs",
	"build": "npm run build-libs && npm run compile-all",
	"release": "npm-run build-debug-normal && node build/release",
	"build-debug-hard": "npm run env-debug-hard && npm run build",
	"build-debug-normal": "npm run env-debug-normal && npm run build",
	"build-debug-light": "npm run env-debug-light && npm run build",
	"build-release-light": "npm run env-release && npm run build",
	"build-release-hard": "build-release-light && node build/release-hard"
};